version: "3.4"

services:
  backend:
    build:
      context: .
      target: dev
    command: sh -c "yarn run test:e2e"
    image: nodefactory/nodejs-ts-starter:${IMAGE_TAG:-latest}
    container_name: "${BACKEND_CONTAINER_NAME:-nodejs-backend}"
    depends_on:
      - db
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules
    ports:
      - "${BACKEND_LOCAL_PORT:-3000}:${SERVER_PORT:-3000}"
      - "${DEBUG_PORT:-56745}:56745"
  db:
    image: postgres:9.6-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    container_name: "${DB_CONTAINER_NAME:-nodejs-db}"
    environment:
      - POSTGRES_USER=${TYPEORM_USER:-nodefactory}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD:-nodefactory}
      - POSTGRES_DB=${TYPEORM_DATABASE:-nodefactory}
    ports:
      - ${DB_LOCAL_PORT:-9999}:5432

volumes:
  node_modules:
  postgres:
